language: csharp
solution: DotNet.MockDb.sln
install:
  - nuget restore DotNet.MockDb.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DotNet.MockDb.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DotNet.MockDb.Tests/bin/Release/DotNet.MockDb.Tests.dll
